version: "3"
services:

  neo4j: 
    image: neo4j:3.5.9
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./theSquareData:/data
    networks:
      - the-square-network

  express:
    image: node:latest
    working_dir: /usr/src/app/theSquareBack
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - "neo4j:neo4j"
    depends_on:
      - neo4j
    volumes:
      - ./theSquareBack:/usr/src/app/theSquareBack
    command: bash -c "npm i && npm run dev"
    networks:
      - the-square-network

  admin-express:
    image: node:latest
    working_dir: /usr/src/app/theSquareAdmin
    ports:
      - "8081:8081"
    expose: 
      - "8081"
    depends_on:
      - neo4j
      - express
    volumes:
      - ./theSquareAdmin:/usr/src/app/theSquareAdmin
    command: bash -c "npm i && npm run dev"
    networks:
      - the-square-network

  # angular:
  #   image: node:latest
  #   working_dir: /usr/src/app/theSquareFront
  #   ports:
  #     - "4200:4200"
  #   expose:
  #     - "4200"
  #   links:
  #     - "express:express"
  #   depends_on:
  #     - neo4j
  #     - express
  #     - admin-express
  #   volumes:
  #     - ./theSquareFront:/usr/src/app/theSquareFront
  #   networks:
  #     - the-square-network
  #   command: bash -c "npm i -g @angular/cli@7.3.6 && npm i && ng serve --host 0.0.0.0 --port 4200"

networks:
  the-square-network: